name: Build and push Docker images

on:
  push:
    tags:
      # 匹配推送 tag 名为 v 开头的事件，如 v1.0,v20.5.3
      - 'v*'

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      # 拉取源码
      - name: Check out the repo
        uses: actions/checkout@v3
      # 安装JDK环境
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: zulu
      - name: Get tag version
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      # 缓存 maven 仓库依赖，提高之后的执行效率
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      # 通过maven构建项目
      - name: Build jar with maven
        run: |
          mvn clean install -Dmaven.test.skip
      # 登录 Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      # 构建并发布到 Docker Hub
      - name: Build docker image and push to Docker Hub
        run: |
          docker build -t codecly/webstack-guns-nkt-docker:${{ steps.vars.outputs.tag }} .
          docker images
          docker tag codecly/webstack-guns-nkt-docker:${{ steps.vars.outputs.tag }} codecly/webstack-guns-nkt-docker:latest
          docker push codecly/webstack-guns-nkt-docker:${{ steps.vars.outputs.tag }}
          docker push codecly/webstack-guns-nkt-docker:latest